[GAME]
  [GAME.classes]
    application = "muforge.game.application:Application"

[game]
node_loader = "muforge.loader:registry"
command_handler = "muforge.engine:run_player_command"
state_provider = "muforge.engine:get_player_state"
[PORTAL]
  [PORTAL.classes]
    application = "muforge.portal.application:Application"
